language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache: pip

before_script:
    - wget --quiet 'http://nicfit.net/files/eyeD3-test-data.tgz'
    - tar xzf ./eyeD3-test-data.tgz -C ./src/test
    - cd ./src/test && ln -sf ./eyeD3-test-data ./data

# command to install dependencies
install:
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .

# command to run tests
script: make coverage

after_success:
  - coveralls


