language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

cache:
    pip: true
    directories:
        - $HOME/eyeD3-test-data.tgz

before_script:
    - make TEST_DATA_DIR=$HOME test-data

# command to install dependencies
install:
    - test $(python -c 'import sys;print("{}{}".format(sys.version_info.major, sys.version_info.minor))') -gt 33 || pip install -r requirements/test_pathlib.txt
    - pip install -U -r requirements/test.txt
    - pip install coveralls
    - pip install -e .

# command to run tests
script: make coverage

after_success:
  - coveralls


