main:
    - dataclasses; python_version < "3.7"
    - filetype
    - deprecation

extra_display-plugin:
    - grako

extra_art-plugin:
    - pylast
    - requests
    - pillow

test:
    - tox
    - pytest
    - pytest-cov
    - pytest-runner
    - factory-boy

dev:
    - nicfit.py[cookiecutter]
    - Sphinx
    - sphinx_rtd_theme
    - twine
    - wheel
    - pyaml
    - pss
    - sphinx-issues
    - git+https://github.com/nicfit/gitchangelog.git
    - cogapp
    - paver
